name: Regression
on:
  workflow_dispatch:
  push:
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  regression-test-benchmark-runner:
    name: Regression Tests
    runs-on: ubuntu-20.04
    env:
      CC: gcc-10
      CXX: g++-10
      GEN: ninja
      BUILD_BENCHMARK: 1
      BUILD_JEMALLOC: 1
      CORE_EXTENSIONS: "json;tpch;tpcds;httpfs;inet"

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
      - name: Checkout old
        uses: actions/checkout@v4
        with:
          repository: 'duckdb/duckdb'
          ref: 'main'
          fetch-depth: 1
          path: old

      # - name: Checkout new
      #   uses: actions/checkout@v4
      #   with:
      #     repository: 'duckdb/duckdb'
      #     ref: 'main'
      #     fetch-depth: 0
      #     path: new
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install
        shell: bash
        run: sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build && pip install requests

      - name: Build
        shell: bash
        run: |
          cd old 
          make
          
          mkdir new
          cd ../new
          make
          cd ..

      - name: Set up benchmarks
        shell: bash
        run: |
          cp -r old/benchmark new/
      # - name: Setup upterm session
      #   uses: owenthereal/action-upterm@v1
      - name: Regression Test RealNest 
        shell: bash
        run: |
          cd old
          mkdir -p duckdb_benchmark_data
          wget -q https://duckdb-blobs.s3.amazonaws.com/data/realnest/realnest.duckdb --output-document=duckdb_benchmark_data/real_nest.duckdb
          mkdir -p ../new/duckdb_benchmark_data
          cp duckdb_benchmark_data/real_nest.duckdb ../new/duckdb_benchmark_data/real_nest.duckdb
          
          echo "benchmark/realnest/17_list_aggregates_histogram_stddev_mode.benchmark" > repro.csv
          echo "benchmark/realnest/17_list_aggregates_histogram.benchmark" >> repro.csv
          echo "benchmark/realnest/17_list_aggregates_mode.benchmark" >> repro.csv
          echo "benchmark/realnest/17_list_aggregates_stddev.benchmark" >> repro.csv

          mv repro.csv .github/regression/
          cp ../test_runner.py scripts/regression/
          cp ../17_* benchmark/realnest/
          
          for i in {1..25}; do
            echo Running iteration $i...
            python scripts/regression/test_runner.py --old=build/release/benchmark/benchmark_runner --new=../new/build/release/benchmark/benchmark_runner --benchmarks=.github/regression/realnest.csv --verbose >> log_file_$i.txt
            cat log_file_$i.txt
            echo Finished iteration $i ✅
          done

      - uses: actions/upload-artifact@v4
        with:
          path: old/log_file*.txt
          name: log_files
